package com.kbz.ccms.workflow;

public enum WorkflowAction {
  ASSIGN_TO_OPERATOR,
  MARK_INCOMPLETE,
  MARK_INSUFFICIENT,
  REJECT_APPLICATION,
  SUBMIT_FOR_APPROVAL,
  FINAL_APPROVE,
  MARK_READY_TO_ISSUE,
  COMPLETE_PICKUP,
  RESUBMIT_TO_HUB
}

